services:
  web:
    image: python:3.6
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app:Z
    working_dir: /app
    command: |
      bash -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
